### ISSUE TITLE
Add a curl get-pip in case it isn't installed?

### ISSUE THREAD

**Issue by cbitstech** [cbitstech/Purple-Robot-Django#19]

**Comment by cbitstech** [comment]
Maybe a:
curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
python get-pip.py

**Comment by audaciouscode** [comment]
There's already a standard mechanism for doing this:

pip install -r requirements.txt

**Comment by audaciouscode** [comment]
If pip not being on the system is the issue, we need to add instructions about how to install a standard copy using Linux distribution packages instead of fetching a blob off of the Internet that won't be upgraded with the rest of the system packages.
