### ISSUE TITLE
config URL requires trailing slash

### ISSUE THREAD

**Issue by afolarin** [cbitstech/Purple-Robot-Django#21]
in the settings (scheme file and app) the Configuration URL doesn't work if there is no trailing "/"
e.g.
http://my.purple-robot.server/pr/config/

**Comment by audaciouscode** [comment]
Haven't been able to replicate and am currently using http://my.purple-robot.server/pr/config in my own deployments with no issues. I suspect this may be caused by confusion in the app about when the user_id parameter is appended to the URL and visible within the settings.
