### ISSUE TITLE
Implement optional feature that "flattens" Django objects into flatter SQL tables in a separate database

### ISSUE THREAD

**Issue by audaciouscode** [cbitstech/Purple-Robot-Django#8]
Users want to point their data analysis programs to PR data, but most programs lack the necessary functionality to parse the JSON that encodes the probe data in a robust and user-friendly way.

Implement a separate management command that iterates over payload objects to inspect the structure of the payload, build/modify flat tables, and insert the probe data into the flat tables.

**Comment by afolarin** [comment]
Queries to the json types in postgres 9.3+ seem to perform ok (but this will depend on how this is being used). 
e.g. heartrate is one of the more expansive datasets, this will extract the timestamp:heartrate pairs

``` sql
select json_array_elements(payload::json->'HEART_TIMESTAMPS') AS HEART_TIMESTAMPS, json_array_elements(payload::json->'HEART') AS HEART from purple_robot_app_purplerobotreading WHERE user_id = 'user-hash' AND probe = 'edu.northwestern.cbits.purple_robot_manager.probes.services.FitbitBetaProbe';
```

**Comment by audaciouscode** [comment]
Implemented. See recent checkins with the extract_into_database command and extractor subcommands.
